# Generated by Django 4.0.4 on 2022-06-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_categoria_delete_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
