# Generated by Django 4.0.4 on 2022-06-22 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
    ]
