# Generated by Django 4.0.4 on 2022-06-22 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_fecha_creacion_post_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publicado',
        ),
    ]
